# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Exporter-Tiny`
	:test-requirement       [ :on "Test::More 0.94"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

