# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Exporter-Tiny`
	:test-requirement       [ :on "Test::More 0.47"^^:CpanId ];
	:runtime-requirement    [ :on "perl 5.006001"^^:CpanId ];
	.

